##################################################
##                                              ##
##  _____ _    _ _____  _____ _                 ##
## / ____| |  | |_   _|/ ____| |                ##
##| |  __| |  | | | | | (___ | |__   ___  _ __  ##
##| | |_ | |  | | | |  \___ \| '_ \ / _ \| '_ \ ##
##| |__| | |__| |_| |_ ____) | | | | (_) | |_) |##
## \_____|\____/|_____|_____/|_| |_|\___/| .__/ ##
##                                       | |    ##
##                                       |_|    ##
##################################################

##################################################
#             Looking for Item Names?            #
##################################################
#           https://tinyurl.com/okqdcvo          #
##################################################

## Tag in chat before text in chat from shop. e.g [GUIShop] Purchase Successful.
prefix: "[&cLoja&f]"

## Command used to open shop, DON'T PUT A /
buy-commands:
  - "buy"
  - "shop"

## Command to open sell inventory, DON'T PUT A /
sell-commands:
  - "sell"

## Register the commands
## if set to false, you must do '/guishopuser buy' instead of '/buy'
register-commands: true

############ Language settings ###############

#No permission message
no-permission: "&cSem permissão!"

#Disabled world message
disabled-world: "&cNão consegues usar a loja deste mundo!"

#Use the escape key to close the shop instead of the back button.
escape-only: true

#Rightclick an item in the shop to open an alternate sell GUI
alternate-sell-enable: true

#The message for the amount you lose, E.G Cost, Or Price
cost: "&7Preço"

#The message for the amount you get back AKA. Sell or Returned
return: "&7Venda"

#The 1st line of the message on shop items
line1: "&8Para vender, clica no item no inv."

#The 2nd line of the message on shop items
line2: "&6Deve ser a mesma quantidade!"

#The 3rd line of the message on shop items
line3: "Clica para comprar a quantidade"

#The 4th line of the message on shop items
line4: "Shift+Click para comprar 1 item"

#The text back button in the shops
back: "&cAtrás"

#The item the back button will be!
back-button-item: "RED_STAINED_GLASS_PANE"

#The messaged displayed before the item amount.

purchased: "&fUma compra foi feita, e &c$"

## The second message displayed when you purchase an item.

## E.G 54$ Taken from your account.
taken: "&f foi tirado da tua conta."

##  The words displayed before the amount needed.
not-enough-pre: "&fPrecisas de mais &c$"

## The words displayed AFTER the amount needed.
not-enough-post: "&f para comprar isto!"

## Text displayed before item name.
sold: "&fOs teus items foram vendidos, e &a$"

##Second message when buying, Words AFTER the amount
## E.G 54$ "Added to your account"
added: "&f foram adicionados à tua conta."

#When something magical goes wrong?
something-wrong: "&fAlguma coisa correu mal, contacta um administrador"

#Message displayed when a player tries to sell blocks not matching the quantity.
in-stacks: "&fPfv vende em stacks de &c"

#Message when a player cannot sell a certain item.
#{count} can be used to display the amount of non sellable, returned items.
cant-sell: "&f(A venda de {count}) item(s) falhou e voltaram ao teu inventário."

#Message when a player cannot buy a certain item.
cant-buy: "&fDesculpa, não podes comprar esse item."

#When a player has a full inventory
full-inventory: "&cPfv, esvazia o teu inventário!"

#The currency symbol
currency: "$"

#The suffix after the currency. E.G Dollars. Yen, etc.
currency-suffix: ""

#The title of a sign that players can click to open shop
sign-title: "[&cGUIShop&f]"

#Do want players to be able to access the shop ONLY using the sign?
signs-only: true

signs-only-message: "&cSó consegues aceder à loja clicando num sinal!"

#Menu row count
menu-rows: 3

#Enable sound on purchase
enable-sound: true

#Purchase sound effect (You can find them here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html)
purchase-sound: "ENTITY_PLAYER_LEVELUP"

#Enable in-game creator.
ingame-config: true

#Enable dynamic pricing
dynamic-pricing: true

#Enable DEBUG mode
debug-mode: false

#The overall shop menu title
menu-title: "Loja"

#The title of a specific shop inventory
shop-title: "Loja &f> &r{shopname}"

#The title of the sell inventory
sell-title: "Loja &f> &rVenda"

#The title of the quantity inventory.
qty-title: "&4Escolhe a quantide"

#The title of the alternate sell GUI, if enabled
alt-sell-title: "Loja &f> &rVenda"

access-to: "&Acesso a comandos:"

buy-lore: "&fCompra: &c{amount}"

sell-lore: "&fVenda: &c{amount}"

free-lore: "&fCompra: &aFREE"

cannot-buy: "&cNão Pode Comprar"

cannot-sell: "&cNão Pode Vender"

forward-page-button-name: "&Próx. pagina"

backward-page-button-name: "&rUltima pagina"

#Used in the alternate sell GUI
alt-sell-indicator-material: "GOLD_INGOT"

alt-sell-add-material: "GREEN_STAINED_GLASS_PANE"
alt-sell-remove-material: "RED_STAINED_GLASS_PANE"

alt-sell-quantity-1: 1
alt-sell-quantity-2: 10
alt-sell-quantity-3: 64

alt-sell-confirm-material: "EMERALD_BLOCK"
alt-sell-cancel-material: "REDSTONE_BLOCK"

alt-sell-confirm-name: "&a&lConfirmar"
alt-sell-cancel-name: "&c&lCancelar"

alt-sell-not-enough: "&cNão tens {amount} items para vender."

DisabledWorlds: -'SurvivalWorld'

## Items to disable quantity stacking.
## This will force these items to only have
## a quantity of 1. Good for swords, armor, etc.
##
## This is an item SEARCH. Meaning it is not the full item name.
## E.G CHESTPLATE blocks ALL chestplates because all items contain
## the word CHESTPLATE.
disabled-qty-items:
  - "CHESTPLATE"
  - "LEGGINGS"
  - "BOOTS"
  - "HELMET"
  - "BOW"
  - "FISHING_ROD"
  - "SHEARS"
  - "NAME_TAG"
  - "SWORD"
  - "AXE"
  - "PICKAXE"
  - "SHOVEL"
  - "SPADE"
  - "HOE"
  - "LEAD"
  - "LEASH"
  - "HORSE_ARMOR"
  - "SADDLE"
  - "BARDING"

##Menu Items
Rows: 3

menu-items:
  Pane0:
    Type: "DUMMY"
    Item: "BLUE_STAINED_GLASS_PANE"
  Pane1:
    Type: "DUMMY"
    Item: "RED_STAINED_GLASS_PANE"
  Pane2:
    Type: "DUMMY"
    Item: "BLUE_STAINED_GLASS_PANE"
  Pane3:
    Type: "DUMMY"
    Item: "RED_STAINED_GLASS_PANE"
  Pane4:
    Type: "DUMMY"
    Item: "BLUE_STAINED_GLASS_PANE"
  Pane5:
    Type: "DUMMY"
    Item: "RED_STAINED_GLASS_PANE"
  Pane6:
    Type: "DUMMY"
    Item: "BLUE_STAINED_GLASS_PANE"
  Pane7:
    Type: "DUMMY"
    Item: "RED_STAINED_GLASS_PANE"
  PaneCornerRight:
    Type: "DUMMY"
    Item: "BLUE_STAINED_GLASS_PANE"
  Pane8:
    Type: "DUMMY"
    Item: "RED_STAINED_GLASS_PANE"
  Hospital:
    Type: "SHOP"
    Enabled: true
    Item: "GOLDEN_APPLE"
    Desc: "&8(&cSaúde e comida&8)"
    Name: "&dHospital"
  Ores:
    Type: "SHOP"
    Enabled: true
    Item: "EMERALD"
    Desc: "&8(&fOres&8)"
    Name: "&aOres"
  FarmingDrops:
    Type: "SHOP"
    Enabled: true
    Item: "WHEAT_SEEDS"
    Desc: "&8(&fFarming&8)"
    Name: "&eFarming/Drops"
  Brewing:
    Type: "SHOP"
    Enabled: true
    Item: "EXPERIENCE_BOTTLE"
    Desc: "&8(&fBrewing&8)"
    Name: "&2Brewing"
  Gear:
    Type: "SHOP"
    Enabled: true
    Item: "DIAMOND_HELMET"
    Desc: "&8(&fGear&8)"
    Name: "&bGear"
  Spawners:
    Type: "SHOP"
    Enabled: true
    Item: "SPAWNER"
    Desc: "&8(&fSpawners&8)"
    Name: "&6Spawners"
  Blocks:
    Type: "SHOP"
    Enabled: true
    Item: "STONE"
    Desc: "&8(&fBlocks&8)"
    Name: "&6Blocks"
  Pane9:
    Type: "DUMMY"
    Item: "RED_STAINED_GLASS_PANE"
  PaneCornerBottomLeft:
    Type: "DUMMY"
    Item: "BLUE_STAINED_GLASS_PANE"
  Pane10:
    Type: "DUMMY"
    Item: "RED_STAINED_GLASS_PANE"
  Pane11:
    Type: "DUMMY"
    Item: "BLUE_STAINED_GLASS_PANE"
  Pane12:
    Type: "DUMMY"
    Item: "RED_STAINED_GLASS_PANE"
  Pane13:
    Type: "DUMMY"
    Item: "BLUE_STAINED_GLASS_PANE"
  Pane14:
    Type: "DUMMY"
    Item: "RED_STAINED_GLASS_PANE"
  Pane15:
    Type: "DUMMY"
    Item: "BLUE_STAINED_GLASS_PANE"
  Pane16:
    Type: "DUMMY"
    Item: "RED_STAINED_GLASS_PANE"
  Pane17:
    Type: "DUMMY"
    Item: "BLUE_STAINED_GLASS_PANE"
  ################################
  ## Developed by pablo67340    ##
  ## If you need any support    ##
  ## https://discord.gg/v7D6pCm ##
  ################################
